export const labels = {
    logIn: 'Login',
    signUp: 'Sign Up',
    chat: 'Chat',
    Chats: 'Chats',
    AllChats: 'All Chats',
    PinnedChat: 'Pinned Chat',
    ArchiveChat: 'Archive Chat',
    Archived: 'Archived',
    Time1020: '10:20 PM',
    Typing: 'Typing...',
    Video: 'Video',
    Audio: 'Audio',
    Chaturl: 'https://dribble.com/dream...',
    Image: 'Image',
    guidelinespdf: 'guidelines.pdf',
    MissedVoiceCall: 'Missed Voice Call',
    MissedVideoCall: 'Missed Voice Call',
    online: 'Online',
    horaceKeene: 'Horace Keene',
    chatViewToday: 'Today, July 24',
    chatLink: "https://www.figma.com/file/QamN",
    checkThisFile: "You can check on this file.",
    helloAlex: "Hello @Alex Good Morning",
    message: 'Hi, there nice to see you again',
    emailaddress: 'Email Address',
    password: 'Password',
    rememberme: 'Remember Me',
    forgetpassword: 'Forgot Password?',
    continuemsg: 'Or continue with',
    donthaveanaccount: "Don't have an account? ",
    newaccount: 'Create a new account ',
    firstName: 'First Name',
    lastName: 'Last Name',
    phNumber: 'Phone Number',
    userName: 'User Name',
    haveanAccount: 'Already have an account?',
    remeberyourPassword: 'You remember your password?',
    resetPassword: 'Reset Password',
    forgetPassword1: 'Forget Password',
    fPmsg: "Don't worry! It happens.Please enter the address associated with your account.",
    createpassword: 'Create New Password',
    cpMsg: 'Your ne password must be different from previous used passwords.',
    changePwd: 'Change Password',
    newPwd: 'New Password',
    confirmPwd: 'Confirm Password',
    verification: 'Verification',
    verifyMsg: 'Enter 6-digit code sent to you phone number ******6698',
    didnotReceivecode: "I didn't receive code.",
    resendCode: 'Resend code.',
    verifyAcc: 'Verify My Account',
    second: '0:30s',
    pwdChanged: 'Password Changed',
    pwdChangedContent: 'Your password has been changed ',
    suceessfully: 'Successfully.',
    backToMyapp: 'Back To My App',
};

