export const labels = {
    logIn: 'Login',
    signUp: 'Sign Up',
    chat: 'Chat',
    Chats: 'Chats',
    AllChats: 'All Chats',
    PinnedChat: 'Pinned Chat',
    ArchiveChat: 'Archive Chat',
    Archived: 'Archived',
    Time1020: '10:20 PM',
    Time0953: '09:53 PM',
    Time0721: '07:21 PM',
    Typing: 'Typing...',
    Video: 'Video',
    Audio: 'Audio',
    Chaturl: 'https://dribble.com/dream...',
    Image: 'Image',
    guidelinespdf: 'guidelines.pdf',
    MissedVoiceCall: 'Missed Voice Call',
    MissedVideoCall: 'Missed Voice Call',
    Group: 'Group',
    Groups: 'Groups',
    Status: 'Status',
    Contact: 'Contact',
    Call: 'Call',
    online: 'Online',
    horaceKeene: 'Horace Keene',
    chatViewToday: 'Today, July 24',
    chatLink: "https://www.figma.com/file/QamN",
    checkThisFile: "You can check on this file.",
    helloAlex: "Hello @Alex Good Morning",
    message: 'Hi, there nice to see you again',
    emailaddress: 'Email Address',
    password: 'Password',
    rememberme: 'Remember Me',
    forgetpassword: 'Forgot Password?',
    continuemsg: 'Or continue with',
    donthaveanaccount: "Don't have an account? ",
    newaccount: 'Create a new account ',
    firstName: 'First Name',
    lastName: 'Last Name',
    phNumber: 'Phone Number',
    userName: 'User Name',
    haveanAccount: 'Already have an account?',
    remeberyourPassword: 'You remember your password?',
    resetPassword: 'Reset Password',
    forgetPassword1: 'Forget Password',
    fPmsg: "Don't worry! It happens.Please enter the address associated with your account.",
    createpassword: 'Create New Password',
    cpMsg: 'Your ne password must be different from previous used passwords.',
    changePwd: 'Change Password',
    newPwd: 'New Password',
    confirmPwd: 'Confirm Password',
    verification: 'Verification',
    verifyMsg: 'Enter 6-digit code sent to you phone number ******6698',
    didnotReceivecode: "I didn't receive code.",
    resendCode: 'Resend code.',
    verifyAcc: 'Verify My Account',
    second: '0:30s',
    pwdChanged: 'Password Changed',
    pwdChangedContent: 'Your password has been changed ',
    suceessfully: 'Successfully.',
    backToMyapp: 'Back To My App',
    dob: 'Date of Birth',
    inivitemsg: 'Invitation Message',
    saveContact: 'Save Contact',
    socialPro: 'Social Profiles',
    pwdandSec: 'Password & Security',
    privacy: 'Privacy',
    notify: 'Notification',
    lang: 'Language',
    manageDev: 'Manage Devices',
    termandCondition: 'Terms & Conditions',
    privacyPolicy: 'Privacy policy',
    deleteAcc: 'Delete Account',
    logout: 'Logout',
    fbLink: 'www.facebook.com',
    googleLink: 'www.googleplus.com',
    twitterLink: 'www.twitter.com',
    linkedinLink: 'www.linkedIn.com',
    youtubeLink: 'www.youtubelink.com',
    fb: 'Facebook',
    googleplus: 'Google+',
    twitter: 'Twitter',
    linkedIn: 'LinkedIn',
    youtube: 'Youtube',
    ViewContact: 'View Contact',
    MarkAsRead: 'Mark as Read',
    MarkVilliams: 'Mark Villiams',
    ElizabethSosa: 'Elizabeth Sosa',
    MichaelHoward: 'Michael Howard',
    HollisTran: 'Hollis Tran',
    JamesAlbert: 'James Albert',
    DinaBrown: 'Dina Brown',
    JudyMercer: 'JudyMercer',
    UIUXDesigner: 'UI UX Designer',
    GraphicsTeam: 'Graphics Team',
    HTMLTeam: 'HTML Team',
    ColumbusStudios: 'Columbus Studio',
    ThemeforestGroup: 'Themeforest Group',
    CompetitionTeam: 'Competition Team',
    CricketTeam: 'Cricket Team',
    Dreamsguys: 'Dreamguys',
    Yesterday: 'Yesterday',
    Aug1523: '15 Aug 2023',
    DebraisTyping: 'Debra is typing...',
    James: 'James:',
    Hollis: 'Hollis:',
    JonesHttps: 'Jones: https://dribble.com/dream..',
    Horace: 'Horace:',
    Smith: 'Smith:',
    Alex: 'Alex:',
    JoinedUsing: '+ 91 9988776655 joined using...',
    AllGroups: 'All Groups',
    PinnedGroups: 'Pinned Groups',
    ArchiveGroup: 'Archive Groups',
    Sticker: 'Sticker',
    Endtoendencrypted: 'End-to-End Encrypted',
    Ringing: 'Ringing',
    DreamsChatVoiceCall: 'Dreamschat Voice Call',
    Decline: 'Decline',
    Accept: 'Accept',
    Message: 'Message',
    AllCalls : 'All Calls',
    Incoming : 'Incoming',
    Outgoing : 'Outgoing',
    Missed : 'Missed',
    Today : 'Today',
    Aug232023 : '23 Aug 2023',
    RemoveFromCallLog : 'Remove From Call Log',
    Block : 'Block',
    DebraJamesHollis : 'Debra, James, Hollis... ',
    GroupMedia : 'Group Media',
    GroupInfo : 'Group Info',
    Search : 'Search',
    MuteNotification : 'Mute Notification',
    Wallpaper : 'Wallpaper',
    Report : 'Report',
    ClearChat : 'Clear Chat',
    GroupDescription : 'Group Description',
    HelloIamUsingDreamsChat : 'Hello, I m using DreamsChat',
    DummyText : 'Group created by James Albert, on 18 Feb 2022 at 1.32 PM',
    Sleeping : 'Sleeping',
    Available : 'Available',
    AtWork : 'At Work',
    CantTalk : "Can't Talk, Whatsapp only",
    Busy : 'Busy',
    GroupSetting : 'Group Setting',
    EditGroupSetting : 'Edit Group Setting',
    SendMessage : 'Send Message',
    AddOtherParticipants : 'Add Other Participants',
    ApproveNewParticipants : 'Approve New Participants',
    EditGroupAdmins : 'Edit Group Admins'
};

