export const labels = {
    logIn: 'Login',
    signUp: 'Sign Up',
    chat: 'Chat',
    Chats: 'Chats',
    AllChats: 'All Chats',
    PinnedChat: 'Pinned Chat',
    ArchiveChat: 'Archive Chat',
    Archived: 'Archived',
    Time1020: '10:20 PM',
    Time0953: '09:53 PM',
    Time0721: '07:21 PM',
    Typing: 'Typing...',
    Video: 'Video',
    Audio: 'Audio',
    Chaturl: 'https://dribble.com/dream...',
    Image: 'Image',
    guidelinespdf: 'guidelines.pdf',
    MissedVoiceCall: 'Missed Voice Call',
    MissedVideoCall: 'Missed Voice Call',
    Group: 'Group',
    Groups: 'Groups',
    Status: 'Status',
    Contact: 'Contact',
    Call: 'Call',
    online: 'Online',
    horaceKeene: 'Horace Keene',
    chatViewToday: 'Today, July 24',
    chatLink: "https://www.figma.com/file/QamN",
    checkThisFile: "You can check on this file.",
    helloAlex: "Hello @Alex Good Morning",
    ViewContact: 'View Contact',
    MarkAsRead: 'Mark as Read',
    MarkVilliams: 'Mark Villiams',
    ElizabethSosa: 'Elizabeth Sosa',
    MichaelHoward: 'Michael Howard',
    HollisTran: 'Hollis Tran',
    JamesAlbert: 'James Albert',
    DinaBrown: 'Dina Brown',
    JudyMercer: 'JudyMercer',
    UIUXDesigner: 'UI UX Designer',
    GraphicsTeam: 'Graphics Team',
    HTMLTeam: 'HTML Team',
    ColumbusStudios: 'Columbus Studio',
    ThemeforestGroup: 'Themeforest Group',
    CompetitionTeam: 'Competition Team',
    CricketTeam: 'Cricket Team',
    Dreamsguys: 'Dreamguys',
    Yesterday: 'Yesterday',
    Aug1523: '15 Aug 2023',
    DebraisTyping: 'Debra is typing...',
    James: 'James:',
    Hollis: 'Hollis:',
    JonesHttps: 'Jones: https://dribble.com/dream..',
    Horace: 'Horace:',
    Smith: 'Smith:',
    Alex: 'Alex:',
    JoinedUsing: '+ 91 9988776655 joined using...',
    AllGroups: 'All Groups',
    PinnedGroups: 'Pinned Groups',
    ArchiveGroup: 'Archive Groups',
    Sticker: 'Sticker',
    Endtoendencrypted: 'End-to-End Encrypted',
    Ringing: 'Ringing',
    DreamsChatVoiceCall : 'Dreamschat Voice Call',
    Decline : 'Decline',
    Accept : 'Accept',
    Message : 'Message',
};



