export const VideoCallUpperImg = require('../../assets/images/png/video-call-upper.png');
export const VideoCallLowerImg = require('../../assets/images/png/video-call-lower.png');
export const ChatBackgroundImg = require('../../assets/images/png/chatBackground.png');
export const Chatimg1Img = require('../../assets/images/png/chatimg1.png');
export const Chatimg2Img = require('../../assets/images/png/chatimg2.png');
export const Chatimg3Img = require('../../assets/images/png/chatimg3.png');
export const Chatimg4Img = require('../../assets/images/png/chatimg4.png');
export const Chatimg5Img = require('../../assets/images/png/chatimg5.png');
export const Chatimg6Img = require('../../assets/images/png/chatimg6.png');
export const Chatimg7Img = require('../../assets/images/png/chatimg7.png');
export const Chatimg8Img = require('../../assets/images/png/chatimg8.png');
export const Chatimg9Img = require('../../assets/images/png/chatimg9.png');
export const GroupImg1Img = require('../../assets/images/png/groupimg1.png');
export const GroupImg2Img = require('../../assets/images/png/groupimg2.png');
export const GroupImg3Img = require('../../assets/images/png/groupimg3.png');
export const GroupImg4Img = require('../../assets/images/png/groupimg4.png');
export const GroupImg5Img = require('../../assets/images/png/groupimg5.png');
export const GroupImg6Img = require('../../assets/images/png/groupimg6.png');
export const GroupImg7Img = require('../../assets/images/png/groupimg7.png');
export const ProfileImg = require('../../assets/images/png/profile.png');
export const PurpleSignalImg = require('../../assets/images/png/purpleSignal.png');
export const GreenSignalImg = require('../../assets/images/png/greenSignal.png');
export const YellowSignalImg = require('../../assets/images/png/yellowSignal.png');
export const BlueSignalImg = require('../../assets/images/png/blueSignal.png');
export const GroupVideoCallImg1 = require('../../assets/images/png/videoCallImg1.png');
export const GroupVideoCallImg2 = require('../../assets/images/png/videoCallImg2.png');
export const GroupVideoCallImg3 = require('../../assets/images/png/videoCallImg3.png');
export const MediaImg1 = require('../../assets/images/png/mediaImg1.png');
export const MediaImg2 = require('../../assets/images/png/mediaImg2.png');
export const MediaImg3 = require('../../assets/images/png/mediaImg3.png');
export const MediaImg4 = require('../../assets/images/png/mediaImg4.png');
export const QrCodeImg = require('../../assets/images/png/qrcode.png');
export const UserImg = require('../../assets/images/png/userImg.png');
export const UsFlagTmg = require('../../assets/images/png/usFlag.png');
export const GrpImg_1 = require('../../assets/images/png/grpImg_1.png');
export const GrpImg_2 = require('../../assets/images/png/grpImg_2.png');
export const DocImg1= require('../../assets/images/png/DocsImg1.png');
export const DocImg2= require('../../assets/images/png/DocsImg2.png');
export const DocImg3= require('../../assets/images/png/DocsImg3.png');
export const DocImg4= require('../../assets/images/png/DocsImg4.png');
export const DocImg5= require('../../assets/images/png/DocsImg5.png');
export const DocImg6= require('../../assets/images/png/DocsImg6.png');
export const DocImg7= require('../../assets/images/png/DocsImg7.png');
export const DocImg8= require('../../assets/images/png/DocsImg8.png');
export const StatusPic1 = require('../../assets/images/png/status-pic1.png');
export const StatusPic2 = require('../../assets/images/png/status-pic2.png');
export const StatusPic3 = require('../../assets/images/png/status-pic3.png');
export const StatusPic4 = require('../../assets/images/png/status-pic4.png');
export const StatusPic5 = require('../../assets/images/png/status-pic5.png');
export const ViewPic1 = require('../../assets/images/png/view-pic1.png')
export const ViewPic2 = require('../../assets/images/png/view-pic2.png')
export const ViewPic3 = require('../../assets/images/png/view-pic3.png')
export const MutePic1 = require('../../assets/images/png/mute-pic1.png')
export const MutePic2 = require('../../assets/images/png/mute-pic2.png')
export const StatusImg1 = require('../../assets/images/png/statusImg1.png')




