export const screenName = {
    WelcomePage: 'WelcomePage',
    LoginEmail: 'LoginEmail',
    ForgetPassword: 'ForgetPassword',
    Verification: 'Verification',
    SignUp: 'SignUp',
    ChatSettings : 'ChatSettings',
    Chats : 'Chats',
    ChatView:'ChatView',
    UserProfile:'UserProfile',
    Group : 'Group',
    GroupChatting : 'GroupChatting',
    GroupChattingAdmin : 'GroupChattingAdmin',
    GroupInfo : 'GroupInfo',
    GroupInfoAdmin : 'GroupInfoAdmin',
    GroupSettingEditContact : 'GroupSettingEditContact',
    SingleAudioCallRing : 'SingleAudioCallRing',
    SingleAudioCallAttend : 'SingleAudioCallAttend',
    Calling : 'Calling',
    SingleVideoCall : 'SingleVideoCall',
    GroupAudioCallAttend : 'GroupAudioCallAttend',
    GroupVideoCallAttend : 'GroupVideoCallAttend',
};