export const screenName = {
    WelcomePage: 'WelcomePage',
    LoginEmail: 'LoginEmail',
    ForgetPassword: 'ForgetPassword',
    Verification: 'Verification',
    SignUp: 'SignUp',
    ChatSettings : 'ChatSettings',
    Chats : 'Chats',
    ChatView:'ChatView',
    UserProfile:'UserProfile',
    CreateNewPassword:'CreateNewPassword',
    AddContact:'AddContact',
    ContactPage: 'ContactPage',
    SettingsScreen:'SettingsScreen',
    SocialProfiles: 'SocialProfiles',
    Password: 'Password',
    Privacy: 'Privacy',
    Profile: 'Profile',
    LastSeen: 'LastSeen',
    Groups: 'Groups',
    PrivacyChat: 'PrivacyChat',
    Group : 'Group',
    GroupChatting : 'GroupChatting',
    GroupChattingAdmin : 'GroupChattingAdmin',
    GroupInfo : 'GroupInfo',
    GroupInfoAdmin : 'GroupInfoAdmin',
    GroupSettingEditContact : 'GroupSettingEditContact',
    SingleAudioCallRing : 'SingleAudioCallRing',
    SingleAudioCallAttend : 'SingleAudioCallAttend',
    Calling : 'Calling',
    SingleVideoCall : 'SingleVideoCall',
    GroupAudioCallAttend : 'GroupAudioCallAttend',
    GroupVideoCallAttend : 'GroupVideoCallAttend',
    Media:'Media',
    Image:'Image',
    ImageView:'ImageView',
    Video:'Video',
    Link:'Link',
    VideoView:'VideoView',
    StarredMsg:'StarredMsg',
    Calls : 'Calls',
    CallHistory : 'CallHistory',
    GroupSettings : 'GroupSettings',
    VerifyCode:'VerifyCode',
    ChooseWallpaper:'ChooseWallpaper',
    Notification: 'Notification',
    TermsAndCondition: 'TermsAndCondition',
    

};