export const screenName = {
    WelcomePage: 'WelcomePage',
    LoginEmail: 'LoginEmail',
    ForgetPassword: 'ForgetPassword',
    Verification: 'Verification',
    SignUp: 'SignUp',
    ChatSettings : 'ChatSettings',
    Chats : 'Chats',
    ChatView:'ChatView',
    UserProfile:'UserProfile',
    CreateNewPassword:'CreateNewPassword',
    AddContact:'AddContact',
    ContactPage: 'ContactPage',
    SettingsScreen:'SettingsScreen',
    SocialProfiles: 'SocialProfiles',
    Password: 'Password',
    Privacy: 'Privacy',
    Profile: 'Profile',
    LastSeen: 'LastSeen',
    Groups: 'Groups',
    PrivacyChat: 'PrivacyChat',

};